FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool wget

COPY . /repo
WORKDIR /repo
RUN ./autogen.sh && ./configure --prefix=/install && make -j8 && make install && chown 0:0 -R /repo

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
COPY --from=builder /repo/.libs/lpcnet_demo /
